// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCsqQATEzbBgL_4PmUWYE2W53MdwlWpoM',
    appId: '1:298592581662:web:42d4cbb1964f148e27d60f',
    messagingSenderId: '298592581662',
    projectId: 'the-gdsc-club-app',
    authDomain: 'the-gdsc-club-app.firebaseapp.com',
    storageBucket: 'the-gdsc-club-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsVeoIPbonPfFqRVAESBLzL-8Gxfrh1ag',
    appId: '1:298592581662:android:fa21ce743b5023d127d60f',
    messagingSenderId: '298592581662',
    projectId: 'the-gdsc-club-app',
    storageBucket: 'the-gdsc-club-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPzBx5DEM5X-9lVAX5Y1T2ymtQLFnfBEc',
    appId: '1:298592581662:ios:15481dc8c31c9b6827d60f',
    messagingSenderId: '298592581662',
    projectId: 'the-gdsc-club-app',
    storageBucket: 'the-gdsc-club-app.appspot.com',
    iosClientId:
        '298592581662-abqedcffdn135oqp287l888c2fad9k1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPzBx5DEM5X-9lVAX5Y1T2ymtQLFnfBEc',
    appId: '1:298592581662:ios:15481dc8c31c9b6827d60f',
    messagingSenderId: '298592581662',
    projectId: 'the-gdsc-club-app',
    storageBucket: 'the-gdsc-club-app.appspot.com',
    iosClientId:
        '298592581662-abqedcffdn135oqp287l888c2fad9k1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.mockApp',
  );
}
